

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3911 = Integer(3911); _sage_const_3 = Integer(3); _sage_const_64 = Integer(64)
q = _sage_const_3911 
FIELD = GF(q)

t = _sage_const_3 
g = FIELD(_sage_const_3 )

load("client.sage")
load("server.sage")
load("additive_lhss.sage")
load("utils.sage")

security = _sage_const_64 
p,q = generate_safe_primes(security)
N = p*q
print("p: {} - q: {}".format(p,q))
print("N: {}".format(N))

p_hat, q_hat = generate_random_primes(security, N)
N_hat = p_hat*q_hat
print("p_hat: {} - q_hat: {}".format(p_hat,q_hat))
print("N_hat: {}".format(N_hat))

